### ISSUE TITLE
Flag texture needs to be converted to DXT1 or DXT5

### ISSUE THREAD

**Issue by StoneBlue** [linuxgurugamer/ActionGroupManager#3]
*Very* minor issue, but the AquilaEnterprises /Flag/AGMFlag.dds is throwing an error stating it is DXT3 format. Should either be changed to one of the other DXT formats, or, are flags supposed to be .png format? vOv

IIRC, I think all toolbar icons should all be .png rather than .dds... vOv ... Cant remember if flags were supposed to be .png also, or not?

**Comment by linuxgurugamer** [comment]
Fixed
