### ISSUE TITLE
Missing buttons

### ISSUE THREAD

**Issue by Sabrewulf** [linuxgurugamer/ActionGroupManager#4]
I can't set custom actions groups in flight even upgrading VAB/SPH.
There's no settings button, no close button, i can't reach some filters buttons

**Comment by linuxgurugamer** [comment]
Is it just not working, or what?
You are very light on information.  A log file is needed.  I don't even know which version of KSP you are running, or whether it is on Windows, OSX or Linux

**Comment by linuxgurugamer** [comment]
Also, please do followups on the forums.  This is not a bug, it's a tech support question
