### ISSUE TITLE
Log spam and performance degradation when AGM window is open

### ISSUE THREAD

**Issue by RayDurand** [linuxgurugamer/ActionGroupManager#5]
When opening the Action Group Manager window in-mission from the toolbar, there is rapid constant log spam stating "Updating Highlight Color (1, 0.7019608, 0)", and heavy framerate losses when trying to move the game camera or currently open GUI panels (e.g. the AGM panel itself or the debug window).

Running KSP.x86_64 version 1.9.1.2788, resolution 1920x1080
OS: Manjaro Linux with XFCE
Mod version: 2.2.6, downloaded from CKAN

Log file:
[KSP.log](https://github.com/linuxgurugamer/ActionGroupManager/files/4842947/KSP.log)

**Comment by linuxgurugamer** [comment]
Should be fixed in 2.2.6.1 (just released)
